markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  parse_block_html: true
  footnote_backlink: '↑'
  syntax_highlighter: rouge
highlighter: rouge
host: 127.0.0.1
exclude: # Files that should be excluded from the Jekyll build.
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - node_modules
  - assets/js/index.js
  - webpack.config.js
  - package.json
  - README.md
  - ignore
  - vendor
  - assets/fonts/**/*.html
sass:
    sass_dir: assets/_sass
    style: compressed
# baseurl: /
paginate: 5
paginate_path: "blog/page:num"

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
# own variables
#
url: https://fabianmoronzirfas.me
name: "fabianmoronzirfas.me"
title: "Fabian Morón Zirfas on the web"